### ISSUE TITLE
Expiring Certificates as regular admin task

### ISSUE THREAD

**Issue by MichaelFBill** [rancher/docs#3874] opened 2022-02-15 10:55 UTC
A customer had the known issue recently with expiring Certificates. They found the resolution after some research in the Troubleshooting section of our documentation. They recommended to include into our documentation that taking care about certificates is a  manual task that needs to be taken care of on a regular basis.
In summary it took them too long to find the relevant content in the Troubleshooting section

**Comment by jtravee** [comment] 2022-02-15 17:18
Hi there, thank you for reporting this. We have this on our roadmap and will be working towards adding it. 
In the meantime, I'm going to close this as a duplicate of [#3767](https://github.com/rancher/docs/issues/3767).

**Closed by jtravee** 2022-02-15 17:18 UTC
Labels: Rancher2

**Comment by sirredbeard** [comment] 2022-02-15 17:28
@MichaelFBill Is there a SURE ticket for this customer issue/request?

**Comment by samjustus** [comment] 2022-05-31 16:24
@MichaelFBill which certs expired, specifically?

**Comment by samjustus** [comment] 2022-06-14 15:15
@MichaelFBill please see question above
