### ISSUE TITLE
Document Windows Logging v2 support

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3141] opened 2021-03-29 19:57 UTC
https://github.com/rancher/rancher/issues/28721
point of contact: Nick

**Comment by nickgerace** [comment] 2021-05-03 15:00
The epic (https://github.com/rancher/docs/issues/3222) is a duplicate of this issue, but I believe both can co-exist since they are already in review.

**Closed** 2021-05-04 01:11 UTC
Labels: [zube]: In Review
