### ISSUE TITLE
Improve documentation of installation requirements (specifically networking)

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#1703] opened 2019-08-30 13:35 UTC
The content under the Installation->Node Requirements->Networking is confusing to users because it conflates port requirements for the Rancher HA install with those for the Kubernetes cluster provisioning.
It also does not specifically document the port requirements for the standalone or HA installation (for example the HA install does not have separate etcd, control plane or worker nodes).

**The following should be considered when improving this documentation:**

1. The "Node Requirements" content under the "Install" section should not be concerned with the requirements for nodes used in provisioned Kubernetes clusters at all. It should document the port requirements for the standalone and HA Rancher install. Specifically it must clearly document what ports need to be open between the three nodes of the HA install and what ports or outbound connections need to be opened to/from the HA nodes or the standalone node.
2. The Page should be renamed from "Node Requirements" to "Installation requirements".
3. Consider getting rid of the tabs used today and move things to separate pages "Hardware requirements", "OS/Docker requirements" and "Network requirements".
4. There should be a separate "Requirements/Prerequisites" page or section under the "Provisioning Kubernetes Clusters" section that deals with the requirements for cluster provisioning:
    - "Network requirements" dealing with port requirements for the different cluster types (the content that today is conflated in the installation requirements).
    - "OS/Docker requirements" may for example have a link to the corresponding page under Rancher installation requirements because they are the same
    - "Hardware requirements" should provide users with a basic idea on how to size the node resources for the different planes of Kubernetes clusters (etcd, cp, workers). It could also have a collection of links to upstream docs like for example https://kubernetes.io/docs/setup/best-practices/cluster-large/ and https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md.

**Comment by mak3r** [comment] 2019-08-30 16:52
Also, if that is getting updated, I find the tabs on the node requirements page to be challenging. Based on the questions I get requesing information on node requirements, people don't seem to know to click on the second 2 tabs. It would be best if those could be setup as direct hyper links or created as subsections (with hyperlinks). Right now we can only link to the parent page and describe how to access the other information
.

**Comment by janeczku** [comment] 2019-08-30 18:03
@mak3r 
Isn’t that captured under point 3 above? Or different tabs?

**Comment by mak3r** [comment] 2019-08-31 18:23
@janeczku Yes. I agree the tabs are not working. I don't mind the tabs per se - if it were possible to send links that landed on the proper tabbed section. I do think it's good to have the information on a single page if the layout and access (via links) were improved.

**Comment by catherineluse** [comment] 2019-10-15 21:15
The problem is that tabs usually indicate that you should read one tab OR the other tab, not one tab AND other tabs.

I'm taking out the tabs for hardware/networking types of requirements, but I'm adding tabs for single node vs. HA requirements because only one tab is applicable for a given use case.

**Comment by catherineluse** [comment] 2019-11-06 17:47
Closing this issue because https://github.com/rancher/docs/pull/1920 was merged

**Closed by catherineluse** 2019-11-06 17:47 UTC
Labels: Conceptual docs, Networking, Nodes, Rancher installation, [zube]: In Review
