### ISSUE TITLE
Drop unsupported cluster types from cluster cloning docs

### ISSUE THREAD

**Issue by dramich** [rancher/docs#1659] opened 2019-08-09 17:05 UTC
The link points to a section on how to modify hosted cluster exported configs which are not supported at this time. https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cloning-clusters/#2-modify-cluster-config

**Comment by catherineluse** [comment] 2019-09-06 16:44
Closing because the issue is addressed by https://github.com/rancher/docs/pull/1718

**Closed by catherineluse** 2019-09-06 16:44 UTC
Labels: priority/0
