### ISSUE TITLE
[Rancher2] (Continue) Add RKE2 as an installation method to Rancher Docs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3157] opened 2021-04-01 01:26 UTC
**Request Summary:**

https://github.com/rancher/docs/issues/3056 only partially fulfils our desire to add RKE2 as an install method to the Rancher2 docs. Could we update https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ so it will list RKE2 as an option?  For the cpu and memory just mirror the requirements rancherd outlines. You can reach out to me for any details needed.

**Details:**

**Comment by mstrent** [comment] 2021-04-06 00:11
Note that the currently-documented workaround to make ingress a daemonset on RKE2 isn't working:
  _Normal   Scheduled  6m59s                  default-scheduler  Successfully assigned kube-system/rke2-ingress-nginx-controller-lfg64 to oly-rancher-52d
  Normal   Pulling    5m21s (x4 over 6m59s)  kubelet            Pulling image "index.docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1"
  Warning  Failed     5m20s (x4 over 6m58s)  kubelet            Failed to pull image "index.docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1": failed to resolve reference "docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     5m20s (x4 over 6m58s)  kubelet            Error: ErrImagePull
  Normal   BackOff    5m4s (x6 over 6m58s)   kubelet            Back-off pulling image "index.docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1"
  Warning  Failed     110s (x20 over 6m58s)  kubelet            Error: ImagePullBackOff_

The issue is being addressed here: (https://github.com/rancher/rke2/issues/493

But in the mean time, the tweak documented at the bottom of this page doesn't work: https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-rke2/

**Comment by catherineluse** [comment] 2021-05-04 14:52
Closing because https://github.com/rancher/docs/pull/3166 was merged

**Closed by catherineluse** 2021-05-04 14:52 UTC
Labels: Rancher2, priority/high
