### ISSUE TITLE
Bad search results

### ISSUE THREAD

**Issue by OmgImAlexis** [rancher/docs#3871] opened 2022-02-13 04:59 UTC
**Summary:**

For some reason the newest 2.6 docs are almost always suggested after the older docs in the search.

**Details:**

Here's an example when searching for "deploy" the green item is `2.6` the others are all for older versions which have a message at the top saying they're the old pages leading to https://github.com/rancher/docs/issues/3870

![image](https://user-images.githubusercontent.com/6525926/153739340-68484f87-7518-4fd3-b3ec-65313bd8b26e.png)

**Comment by btat** [comment] 2022-02-14 22:27
Hi there, thank you for reporting this. We currently have improved search (specifically, contextual search where only results relevant to the current selected version are displayed) on our roadmap and will be working towards adding it.

In the meantime, I'm going to close this as a duplicate of https://github.com/rancher/docs/issues/3314

**Closed by btat** 2022-02-14 22:27 UTC
